[build]
  command = "make build"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/bymi15/go-mongo-serverless-crud-boilerplate"
  GO111MODULE = "on"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200